const resources = [
    {
        id: 1,
        category: "Programming/Development",
        subcategory: "Guides and Tutorials",
        title: "MDN Web Docs - JavaScript Guide",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
        description: "Comprehensive guide to JavaScript fundamentals and advanced concepts from Mozilla.",
        tags: ["Beginner", "Free"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.9,
        votes: 1250
    },
    {
        id: 2,
        category: "Programming/Development",
        subcategory: "Guides and Tutorials",
        title: "React Official Tutorial",
        url: "https://react.dev/learn",
        description: "Official React documentation with interactive examples and step-by-step tutorial.",
        tags: ["Free", "Interactive"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 980
    },
    {
        id: 3,
        category: "Programming/Development",
        subcategory: "Guides and Tutorials",
        title: "TypeScript Handbook",
        url: "https://www.typescriptlang.org/docs/",
        description: "Official TypeScript documentation covering types, interfaces, and advanced patterns.",
        tags: ["Free", "AI"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: true,
        rating: 4.7,
        votes: 720
    },
    {
        id: 4,
        category: "Programming/Development",
        subcategory: "Tools and Softwares",
        title: "Visual Studio Code",
        url: "https://code.visualstudio.com/",
        description: "Powerful code editor with built-in debugging, Git integration, and extensions.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.9,
        votes: 2100
    },
    {
        id: 5,
        category: "Programming/Development",
        subcategory: "Tools and Softwares",
        title: "GitHub",
        url: "https://github.com",
        description: "Platform for version control and collaboration with millions of developers.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.8,
        votes: 1850
    },
    {
        id: 6,
        category: "Programming/Development",
        subcategory: "Tools and Softwares",
        title: "Docker Desktop",
        url: "https://www.docker.com/products/docker-desktop/",
        description: "Containerization platform for building and sharing containerized applications.",
        tags: ["Free", "Advanced"],
        type: "tool",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.6,
        votes: 890
    },
    {
        id: 7,
        category: "Programming/Development",
        subcategory: "FAQs and Basics",
        title: "What is an API?",
        url: "https://www.redhat.com/en/topics/api/what-is-a-rest-api",
        description: "Beginner's guide to understanding APIs and how they work.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 340
    },
    {
        id: 8,
        category: "Programming/Development",
        subcategory: "FAQs and Basics",
        title: "Git Basics Explained",
        url: "https://rogerdudler.github.io/git-guide/",
        description: "Simple and clear Git guide for beginners covering essential commands.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 520
    },
    {
        id: 9,
        category: "Programming/Development",
        subcategory: "Common Mistakes/Issues",
        title: "Fixing CORS Errors",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS",
        description: "Understanding and resolving Cross-Origin Resource Sharing errors.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.4,
        votes: 410
    },
    {
        id: 10,
        category: "Programming/Development",
        subcategory: "Common Mistakes/Issues",
        title: "JavaScript Null vs Undefined",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
        description: "Guide to understanding the difference between null and undefined in JavaScript.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 280
    },
    {
        id: 11,
        category: "Programming/Development",
        subcategory: "Guides and Tutorials",
        title: "Node.js Complete Guide",
        url: "https://nodejs.org/en/docs/guides/",
        description: "Official Node.js documentation and guides for backend development.",
        tags: ["Free", "Backend"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.7,
        votes: 650
    },
    {
        id: 12,
        category: "Programming/Development",
        subcategory: "Tools and Softwares",
        title: "Postman",
        url: "https://www.postman.com/",
        description: "API development and testing tool for building and consuming APIs.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 780
    },
    {
        id: 13,
        category: "Programming/Development",
        subcategory: "Common Mistakes/Issues",
        title: "Fixing Memory Leaks in Node.js",
        url: "https://nodejs.org/en/docs/guides/diagnostics/",
        description: "Diagnose and fix memory leaks in Node.js applications.",
        tags: ["Error", "Advanced"],
        type: "error",
        difficulty: "Advanced",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 190
    },
    {
        id: 14,
        category: "Programming/Development",
        subcategory: "Guides and Tutorials",
        title: "Python for Everybody",
        url: "https://www.python.org/about/gettingstarted/",
        description: "Comprehensive Python tutorial for beginners to advanced.",
        tags: ["Free", "Beginner"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.9,
        votes: 1100
    },
    {
        id: 15,
        category: "UI/UX Design",
        subcategory: "Guides and Tutorials",
        title: "Figma Complete Guide",
        url: "https://www.figma.com/resource-library/guide/",
        description: "Comprehensive tutorial series for learning Figma from basics to advanced.",
        tags: ["Free", "Essential"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 920
    },
    {
        id: 16,
        category: "UI/UX Design",
        subcategory: "Guides and Tutorials",
        title: "Google Material Design",
        url: "https://m3.material.io/",
        description: "Google's design system with guidelines, components, and color tools.",
        tags: ["Free", "Design System"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.7,
        votes: 680
    },
    {
        id: 17,
        category: "UI/UX Design",
        subcategory: "Guides and Tutorials",
        title: "UX Design Principles",
        url: "https://www.interaction-design.org/literature/article/human-design-principles",
        description: "Introduction to fundamental design principles for better user experiences.",
        tags: ["Beginner", "Free"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 420
    },
    {
        id: 18,
        category: "UI/UX Design",
        subcategory: "Tools and Softwares",
        title: "Figma",
        url: "https://www.figma.com/",
        description: "Collaborative interface design tool for teams with real-time editing.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.9,
        votes: 1500
    },
    {
        id: 19,
        category: "UI/UX Design",
        subcategory: "Tools and Softwares",
        title: "Adobe XD",
        url: "https://www.adobe.com/products/xd.html",
        description: "Vector-based UX design tool for prototyping and sharing designs.",
        tags: ["Free", "Adobe"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 380
    },
    {
        id: 20,
        category: "UI/UX Design",
        subcategory: "Tools and Softwares",
        title: "Framer",
        url: "https://www.framer.com/",
        description: "Interactive design tool with powerful prototyping features.",
        tags: ["Free", "Advanced"],
        type: "tool",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: true,
        isNew: true,
        rating: 4.7,
        votes: 520
    },
    {
        id: 21,
        category: "UI/UX Design",
        subcategory: "FAQs and Basics",
        title: "Color Theory Basics",
        url: "https://www.colormatters.com/color-theory",
        description: "Understanding colors and how to use them effectively in design.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 290
    },
    {
        id: 22,
        category: "UI/UX Design",
        subcategory: "FAQs and Basics",
        title: "Typography Fundamentals",
        url: "https://material.io/design/typography/the-type-system.html",
        description: "Learn typography principles and how to choose fonts.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 210
    },
    {
        id: 23,
        category: "UI/UX Design",
        subcategory: "Common Mistakes/Issues",
        title: "Fixing Font Rendering Issues",
        url: "https://fonts.google.com/specimen/Roboto",
        description: "Solutions for common font display problems across different browsers.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.2,
        votes: 150
    },
    {
        id: 24,
        category: "UI/UX Design",
        subcategory: "Common Mistakes/Issues",
        title: "Responsive Design Breakpoints",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_breakpoints",
        description: "Guide to setting correct breakpoints for responsive layouts.",
        tags: ["Error", "Responsive"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 180
    },
    {
        id: 25,
        category: "UI/UX Design",
        subcategory: "Tools and Softwares",
        title: "Miro",
        url: "https://miro.com/",
        description: "Online collaborative whiteboard for design thinking and planning.",
        tags: ["Free", "Collaboration"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 440
    },
    {
        id: 26,
        category: "UI/UX Design",
        subcategory: "Guides and Tutorials",
        title: "Design Systems Handbook",
        url: "https://www.designsystems.com/",
        description: "Comprehensive guide to building and maintaining design systems.",
        tags: ["Free", "Advanced"],
        type: "tutorial",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.8,
        votes: 360
    },
    {
        id: 27,
        category: "Marketing",
        subcategory: "Guides and Tutorials",
        title: "Google Analytics 4 Tutorial",
        url: "https://support.google.com/analytics/answer/10089679",
        description: "Official guide to setting up and using Google Analytics 4.",
        tags: ["Free", "Essential"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.6,
        votes: 580
    },
    {
        id: 28,
        category: "Marketing",
        subcategory: "Guides and Tutorials",
        title: "SEO Starter Guide",
        url: "https://developers.google.com/search/docs/fundamentals",
        description: "Google's official SEO guide for improving search rankings.",
        tags: ["Free", "SEO"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 720
    },
    {
        id: 29,
        category: "Marketing",
        subcategory: "Guides and Tutorials",
        title: "Content Marketing Institute",
        url: "https://contentmarketinginstitute.com/what-is-content-marketing/",
        description: "Introduction to content marketing strategies and best practices.",
        tags: ["Free", "Content"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 340
    },
    {
        id: 30,
        category: "Marketing",
        subcategory: "Tools and Softwares",
        title: "Mailchimp",
        url: "https://mailchimp.com/",
        description: "Email marketing platform with automation and analytics tools.",
        tags: ["Free", "Email"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 820
    },
    {
        id: 31,
        category: "Marketing",
        subcategory: "Tools and Softwares",
        title: "Hootsuite",
        url: "https://www.hootsuite.com/",
        description: "Social media management platform for scheduling and analytics.",
        tags: ["Free", "Social"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 460
    },
    {
        id: 32,
        category: "Marketing",
        subcategory: "Tools and Softwares",
        title: "SEMrush",
        url: "https://www.semrush.com/",
        description: "All-in-one toolkit for digital marketing and SEO.",
        tags: ["Paid", "SEO"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 620
    },
    {
        id: 33,
        category: "Marketing",
        subcategory: "FAQs and Basics",
        title: "Email Marketing Best Practices",
        url: "https://www.mailchimp.com/resources/email-marketing-best-practices/",
        description: "Essential tips for effective email marketing campaigns.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 280
    },
    {
        id: 34,
        category: "Marketing",
        subcategory: "FAQs and Basics",
        title: "What is PPC Advertising?",
        url: "https://www.wordstream.com/ppc-advertising",
        description: "Understanding pay-per-click advertising basics.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 190
    },
    {
        id: 35,
        category: "Marketing",
        subcategory: "Common Mistakes/Issues",
        title: "Fixing Low Email Open Rates",
        url: "https://www.campaignmonitor.com/blog/low-email-open-rates/",
        description: "Solutions for improving email engagement and open rates.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 220
    },
    {
        id: 36,
        category: "Marketing",
        subcategory: "Common Mistakes/Issues",
        title: "Common SEO Mistakes",
        url: "https://www.searchenginejournal.com/common-seo-mistakes/",
        description: "List of frequent SEO errors and how to avoid them.",
        tags: ["Error", "SEO"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 310
    },
    {
        id: 37,
        category: "Marketing",
        subcategory: "Tools and Softwares",
        title: "Ahrefs",
        url: "https://ahrefs.com/",
        description: "SEO toolset for backlinks analysis and keyword research.",
        tags: ["Paid", "SEO"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 740
    },
    {
        id: 38,
        category: "Marketing",
        subcategory: "Guides and Tutorials",
        title: "Social Media Marketing Guide",
        url: "https://buffer.com/library/social-media-marketing/",
        description: "Complete guide to social media marketing strategies.",
        tags: ["Free", "Social"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 420
    },
    {
        id: 39,
        category: "Product and Project Management",
        subcategory: "Guides and Tutorials",
        title: "Agile Methodology Guide",
        url: "https://www.atlassian.com/agile",
        description: "Comprehensive guide to Agile and Scrum methodologies.",
        tags: ["Free", "Agile"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 680
    },
    {
        id: 40,
        category: "Product and Project Management",
        subcategory: "Guides and Tutorials",
        title: "Product Management 101",
        url: "https://www.productplan.com/product-management-101/",
        description: "Introduction to product management roles and responsibilities.",
        tags: ["Beginner", "Free"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 520
    },
    {
        id: 41,
        category: "Product and Project Management",
        subcategory: "Guides and Tutorials",
        title: "Sprint Planning Guide",
        url: "https://www.scrum.org/resources/sprint-planning",
        description: "How to run effective sprint planning meetings.",
        tags: ["Free", "Scrum"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 340
    },
    {
        id: 42,
        category: "Product and Project Management",
        subcategory: "Tools and Softwares",
        title: "Jira",
        url: "https://www.atlassian.com/software/jira",
        description: "Project management and issue tracking tool for agile teams.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 920
    },
    {
        id: 43,
        category: "Product and Project Management",
        subcategory: "Tools and Softwares",
        title: "Trello",
        url: "https://trello.com/",
        description: "Visual project management with boards, lists, and cards.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 840
    },
    {
        id: 44,
        category: "Product and Project Management",
        subcategory: "Tools and Softwares",
        title: "Notion",
        url: "https://www.notion.so/",
        description: "All-in-one workspace for notes, docs, and project management.",
        tags: ["Free", "Productivity"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 1100
    },
    {
        id: 45,
        category: "Product and Project Management",
        subcategory: "FAQs and Basics",
        title: "Kanban vs Scrum",
        url: "https://www.atlassian.com/agile/kanban/scrum-vs-kanban",
        description: "Comparison of popular agile methodologies.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 380
    },
    {
        id: 46,
        category: "Product and Project Management",
        subcategory: "FAQs and Basics",
        title: "What is a Product Roadmap?",
        url: "https://www.productplan.com/what-is-a-product-roadmap/",
        description: "Understanding product roadmaps and their importance.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 260
    },
    {
        id: 47,
        category: "Product and Project Management",
        subcategory: "Common Mistakes/Issues",
        title: "Managing Scope Creep",
        url: "https://www.projectmanager.com/blog/scope-creep",
        description: "Strategies for controlling project scope and requirements.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 190
    },
    {
        id: 48,
        category: "Product and Project Management",
        subcategory: "Common Mistakes/Issues",
        title: "Prioritization Frameworks",
        url: "https://www.producthunt.com/post/prioritization-frameworks-for-pms",
        description: "Overview of popular prioritization methods like RICE and MoSCoW.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 270
    },
    {
        id: 49,
        category: "Product and Project Management",
        subcategory: "Tools and Softwares",
        title: "Asana",
        url: "https://asana.com/",
        description: "Work management platform for teams to track goals and projects.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 680
    },
    {
        id: 50,
        category: "Product and Project Management",
        subcategory: "Guides and Tutorials",
        title: "User Story Mapping Guide",
        url: "https://www.jpattonassociates.com/user-story-mapping/",
        description: "Learn how to create effective user story maps.",
        tags: ["Free", "Agile"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 220
    },
    {
        id: 51,
        category: "Business and Finance",
        subcategory: "Guides and Tutorials",
        title: "Financial Modeling Guide",
        url: "https://corporatefinanceinstitute.com/courses/financial-modeling/",
        description: "Learn how to build financial models from scratch.",
        tags: ["Free", "Finance"],
        type: "tutorial",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.7,
        votes: 480
    },
    {
        id: 52,
        category: "Business and Finance",
        subcategory: "Guides and Tutorials",
        title: "Startup Funding Guide",
        url: "https://www.ycombinator.com/library/",
        description: "Y Combinator's guide to startup funding and growth.",
        tags: ["Free", "Startup"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 620
    },
    {
        id: 53,
        category: "Business and Finance",
        subcategory: "Guides and Tutorials",
        title: "Business Model Canvas",
        url: "https://strategyzer.com/canvas/business-model-canvas/",
        description: "Learn to create and analyze business models.",
        tags: ["Free", "Startup"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 380
    },
    {
        id: 54,
        category: "Business and Finance",
        subcategory: "Tools and Softwares",
        title: "QuickBooks",
        url: "https://quickbooks.intuit.com/",
        description: "Accounting software for small businesses.",
        tags: ["Paid", "Accounting"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 720
    },
    {
        id: 55,
        category: "Business and Finance",
        subcategory: "Tools and Softwares",
        title: "Xero",
        url: "https://www.xero.com/",
        description: "Cloud-based accounting platform for small businesses.",
        tags: ["Paid", "Accounting"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 540
    },
    {
        id: 56,
        category: "Business and Finance",
        subcategory: "Tools and Softwares",
        title: "Wave",
        url: "https://www.waveapps.com/",
        description: "Free accounting software for small businesses.",
        tags: ["Free", "Accounting"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 420
    },
    {
        id: 57,
        category: "Business and Finance",
        subcategory: "FAQs and Basics",
        title: "Understanding P&L Statements",
        url: "https://www.investopedia.com/terms/p/profit-and-loss-statement.asp",
        description: "Guide to reading and creating profit and loss statements.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 320
    },
    {
        id: 58,
        category: "Business and Finance",
        subcategory: "FAQs and Basics",
        title: "Cash Flow Management",
        url: "https://www.fundera.com/blog/cash-flow-management-guide",
        description: "Essential tips for managing business cash flow.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 240
    },
    {
        id: 59,
        category: "Business and Finance",
        subcategory: "Common Mistakes/Issues",
        title: "Common Accounting Errors",
        url: "https://www.accountingtools.com/articles/common-accounting-errors",
        description: "Frequent accounting mistakes and how to avoid them.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 180
    },
    {
        id: 60,
        category: "Business and Finance",
        subcategory: "Common Mistakes/Issues",
        title: "Tax Deduction Mistakes",
        url: "https://www.turbotax.com/tax-deductions/common-mistakes",
        description: "Common tax errors small businesses should avoid.",
        tags: ["Error", "Tax"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 210
    },
    {
        id: 61,
        category: "Business and Finance",
        subcategory: "Tools and Softwares",
        title: "Stripe",
        url: "https://stripe.com/",
        description: "Payment processing platform for internet businesses.",
        tags: ["Free", "Payments"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.8,
        votes: 860
    },
    {
        id: 62,
        category: "Business and Finance",
        subcategory: "Guides and Tutorials",
        title: "SaaS Metrics Guide",
        url: "https://www.forentrepreneurs.com/saas-metrics-2/",
        description: "Essential metrics for SaaS business metrics.",
        tags: ["Free", "SaaS"],
        type: "tutorial",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.7,
        votes: 340
    },
    {
        id: 63,
        category: "Sales and Growth",
        subcategory: "Guides and Tutorials",
        title: "Sales Methodology Guide",
        url: "https://www.salesforce.com/resources/articles/sales-methodology/",
        description: "Overview of popular sales methodologies and frameworks.",
        tags: ["Free", "Sales"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.6,
        votes: 480
    },
    {
        id: 64,
        category: "Sales and Growth",
        subcategory: "Guides and Tutorials",
        title: "Growth Hacking 101",
        url: "https://growthhackers.com/growth-hacking-101",
        description: "Introduction to growth hacking strategies for startups.",
        tags: ["Free", "Growth"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 360
    },
    {
        id: 65,
        category: "Sales and Growth",
        subcategory: "Guides and Tutorials",
        title: "Cold Email Mastery",
        url: "https://www.woodpecker.co/cold-email-guide",
        description: "Complete guide to cold email outreach.",
        tags: ["Free", "Email"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 290
    },
    {
        id: 66,
        category: "Sales and Growth",
        subcategory: "Tools and Softwares",
        title: "Salesforce",
        url: "https://www.salesforce.com/",
        description: "Leading CRM platform for sales and customer relationship management.",
        tags: ["Paid", "Essential"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 920
    },
    {
        id: 67,
        category: "Sales and Growth",
        subcategory: "Tools and Softwares",
        title: "HubSpot CRM",
        url: "https://www.hubspot.com/products/crm",
        description: "Free CRM with sales, marketing, and service tools.",
        tags: ["Free", "Essential"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 1100
    },
    {
        id: 68,
        category: "Sales and Growth",
        subcategory: "Tools and Softwares",
        title: "LinkedIn Sales Navigator",
        url: "https://www.linkedin.com/products/sales-navigator",
        description: "Advanced search and insights for B2B sales.",
        tags: ["Paid", "B2B"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 440
    },
    {
        id: 69,
        category: "Sales and Growth",
        subcategory: "FAQs and Basics",
        title: "Sales Funnel Explained",
        url: "https://www.smartinsights.com/marketing-sales/sales-funnel/",
        description: "Understanding the customer journey through the sales funnel.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 340
    },
    {
        id: 70,
        category: "Sales and Growth",
        subcategory: "FAQs and Basics",
        title: "Cold Calling Tips",
        url: "https://www.salescoach.org/cold-calling-tips",
        description: "Best practices for successful cold calling.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 220
    },
    {
        id: 71,
        category: "Sales and Growth",
        subcategory: "Common Mistakes/Issues",
        title: "Common Sales Objections",
        url: "https://www.saleshunter.com/sales-objections",
        description: "How to handle and overcome common sales objections.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 280
    },
    {
        id: 72,
        category: "Sales and Growth",
        subcategory: "Common Mistakes/Issues",
        title: "Closing Techniques",
        url: "https://www.closes.com/closing-techniques",
        description: "Effective sales closing methods and mistakes to avoid.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 320
    },
    {
        id: 73,
        category: "Sales and Growth",
        subcategory: "Tools and Softwares",
        title: "ZoomInfo",
        url: "https://www.zoominfo.com/",
        description: "B2B contact database for prospect research.",
        tags: ["Paid", "B2B"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 380
    },
    {
        id: 74,
        category: "Sales and Growth",
        subcategory: "Guides and Tutorials",
        title: "Account-Based Marketing",
        url: "https://www.forrester.com/b2b-marketing/accountbased-marketing",
        description: "Guide to ABM strategies and implementation.",
        tags: ["Free", "B2B"],
        type: "tutorial",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 190
    },
    {
        id: 75,
        category: "Events and Community",
        subcategory: "Guides and Tutorials",
        title: "Event Planning Guide",
        url: "https://www.eventbrite.com/blog/event-planning-guide/",
        description: "Complete guide to planning successful events.",
        tags: ["Free", "Events"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 420
    },
    {
        id: 76,
        category: "Events and Community",
        subcategory: "Guides and Tutorials",
        title: "Community Building 101",
        url: "https://www.communitybuildingguide.com/",
        description: "Strategies for building and engaging online communities.",
        tags: ["Free", "Community"],
        type: "tutorial",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 380
    },
    {
        id: 77,
        category: "Events and Community",
        subcategory: "Guides and Tutorials",
        title: "Virtual Event Handbook",
        url: "https://www.notion.so/event-handbook",
        description: "Guide to planning and executing virtual events.",
        tags: ["Free", "Virtual"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: true,
        rating: 4.5,
        votes: 240
    },
    {
        id: 78,
        category: "Events and Community",
        subcategory: "Tools and Softwares",
        title: "Eventbrite",
        url: "https://www.eventbrite.com/",
        description: "Platform for creating and discovering events.",
        tags: ["Free", "Events"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 680
    },
    {
        id: 79,
        category: "Events and Community",
        subcategory: "Tools and Softwares",
        title: "Meetup",
        url: "https://www.meetup.com/",
        description: "Platform for organizing and joining local groups and events.",
        tags: ["Free", "Events"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 520
    },
    {
        id: 80,
        category: "Events and Community",
        subcategory: "Tools and Softwares",
        title: "Luma",
        url: "https://www.lumaevents.com/",
        description: "Professional event management platform.",
        tags: ["Paid", "Events"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 180
    },
    {
        id: 81,
        category: "Events and Community",
        subcategory: "FAQs and Basics",
        title: "Event Marketing Tips",
        url: "https://www.eventmarketer.com/event-marketing-guide",
        description: "How to promote your event effectively.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 220
    },
    {
        id: 82,
        category: "Events and Community",
        subcategory: "FAQs and Basics",
        title: "Community Management Basics",
        url: "https://www.maven.co/community-management-guide",
        description: "Introduction to managing online communities.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 160
    },
    {
        id: 83,
        category: "Events and Community",
        subcategory: "Common Mistakes/Issues",
        title: "Low Event Attendance",
        url: "https://www.eventbrite.com/blog/low-attendance",
        description: "Solutions for improving event turnout.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 190
    },
    {
        id: 84,
        category: "Events and Community",
        subcategory: "Common Mistakes/Issues",
        title: "Engagement Strategies",
        url: "https://www.communityroundtable.com/engagement",
        description: "Ways to increase community member engagement.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 240
    },
    {
        id: 85,
        category: "Events and Community",
        subcategory: "Tools and Softwares",
        title: "Discord",
        url: "https://discord.com/",
        description: "Communication platform for online communities.",
        tags: ["Free", "Community"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 920
    },
    {
        id: 86,
        category: "Events and Community",
        subcategory: "Guides and Tutorials",
        title: "Hybrid Events Guide",
        url: "https://www.bizzabo.com/blog/hybrid-events",
        description: "Planning guide for hybrid in-person and virtual events.",
        tags: ["Free", "Hybrid"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 180
    },
    {
        id: 87,
        category: "Programming/Development",
        subcategory: "Guides and Tutorials",
        title: "Rust Programming Book",
        url: "https://doc.rust-lang.org/book/",
        description: "The official book on learning Rust programming.",
        tags: ["Free", "Systems"],
        type: "tutorial",
        difficulty: "Advanced",
        isPremium: false,
        isTrending: true,
        isNew: true,
        rating: 4.8,
        votes: 440
    },
    {
        id: 88,
        category: "Programming/Development",
        subcategory: "Tools and Softwares",
        title: "Cursor AI",
        url: "https://cursor.sh/",
        description: "AI-first code editor built for pair programming with AI.",
        tags: ["Free", "AI"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: true,
        rating: 4.7,
        votes: 680
    },
    {
        id: 89,
        category: "Programming/Development",
        subcategory: "Tools and Softwares",
        title: "Warp Terminal",
        url: "https://www.warp.dev/",
        description: "Modern terminal with AI command completion.",
        tags: ["Free", "AI"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: true,
        rating: 4.6,
        votes: 320
    },
    {
        id: 90,
        category: "Programming/Development",
        subcategory: "Common Mistakes/Issues",
        title: "Debugging React useEffect Loops",
        url: "https://react.dev/reference/react/useEffect",
        description: "How to debug and fix infinite loops in React useEffect.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 260
    },
    {
        id: 91,
        category: "UI/UX Design",
        subcategory: "Tools and Softwares",
        title: "Principle",
        url: "https://principleformac.com/",
        description: "Design tool for creating animated interfaces.",
        tags: ["Paid", "Mac"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 280
    },
    {
        id: 92,
        category: "UI/UX Design",
        subcategory: "Common Mistakes/Issues",
        title: "Fixing CSS Grid Layout Issues",
        url: "https://css-tricks.com/snippets/css/complete-guide-grid/",
        description: "Common CSS Grid problems and their solutions.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.4,
        votes: 190
    },
    {
        id: 93,
        category: "Marketing",
        subcategory: "Tools and Softwares",
        title: "Buffer",
        url: "https://buffer.com/",
        description: "Social media scheduling and management tool.",
        tags: ["Free", "Social"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 540
    },
    {
        id: 94,
        category: "Product and Project Management",
        subcategory: "Tools and Softwares",
        title: "Linear",
        url: "https://linear.app/",
        description: "Issue tracking for modern software teams.",
        tags: ["Free", "GitHub"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: true,
        rating: 4.7,
        votes: 420
    },
    {
        id: 95,
        category: "Business and Finance",
        subcategory: "Tools and Softwares",
        title: "BambooHR",
        url: "https://www.bamboohr.com/",
        description: "HR software for growing businesses.",
        tags: ["Paid", "HR"],
        type: "tool",
        difficulty: "Intermediate",
        isPremium: true,
        isTrending: false,
        isNew: false,
        rating: 4.5,
        votes: 320
    },
    {
        id: 96,
        category: "Sales and Growth",
        subcategory: "Tools and Softwares",
        title: "Gong",
        url: "https://www.gong.io/",
        description: "Revenue intelligence platform for sales teams.",
        tags: ["Paid", "AI"],
        type: "tool",
        difficulty: "Advanced",
        isPremium: true,
        isTrending: true,
        isNew: false,
        rating: 4.6,
        votes: 380
    },
    {
        id: 97,
        category: "Events and Community",
        subcategory: "Tools and Softwares",
        title: "Circle",
        url: "https://circle.so/",
        description: "Community platform for creators and brands.",
        tags: ["Free", "Community"],
        type: "tool",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.6,
        votes: 340
    },
    {
        id: 98,
        category: "Programming/Development",
        subcategory: "FAQs and Basics",
        title: "HTTP Status Codes",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
        description: "Complete reference for HTTP status codes.",
        tags: ["Beginner", "Free"],
        type: "faq",
        difficulty: "Beginner",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.6,
        votes: 380
    },
    {
        id: 99,
        category: "Programming/Development",
        subcategory: "Common Mistakes/Issues",
        title: "Fixing Promise.all Errors",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all",
        description: "Handle errors properly in Promise.all.",
        tags: ["Error", "Fix"],
        type: "error",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: false,
        isNew: false,
        rating: 4.3,
        votes: 180
    },
    {
        id: 100,
        category: "UI/UX Design",
        subcategory: "Guides and Tutorials",
        title: "Accessibility (a11y) Guide",
        url: "https://www.w3.org/WAI/fundamentals/accessibility-intro/",
        description: "Web Content Accessibility Guidelines.",
        tags: ["Free", "A11y"],
        type: "tutorial",
        difficulty: "Intermediate",
        isPremium: false,
        isTrending: true,
        isNew: false,
        rating: 4.7,
        votes: 420
    }
];

const categories = [
    { id: 1, name: "Programming/Development", slug: "programming-development", icon: "</>", color: "#22D3EE", description: "Programming languages, frameworks, and development tools" },
    { id: 2, name: "UI/UX Design", slug: "ui-ux-design", icon: "◐", color: "#A855F7", description: "Design tools, principles, and user experience" },
    { id: 3, name: "Marketing", slug: "marketing", icon: "📈", color: "#F97316", description: "Digital marketing, SEO, and content strategies" },
    { id: 4, name: "Product and Project Management", slug: "product-project-management", icon: "⚡", color: "#6366F1", description: "Product management and agile methodologies" },
    { id: 5, name: "Business and Finance", slug: "business-finance", icon: "💰", color: "#10B981", description: "Business planning, accounting, and financial tools" },
    { id: 6, name: "Sales and Growth", slug: "sales-growth", icon: "🚀", color: "#F43F5E", description: "Sales strategies and growth hacking" },
    { id: 7, name: "Events and Community", slug: "events-community", icon: "📅", color: "#FBBF24", description: "Event planning and community building" }
];

const subcategories = [
    "Guides and Tutorials",
    "Tools and Softwares", 
    "FAQs and Basics",
    "Common Mistakes/Issues"
];

const tags = ["Beginner", "Free", "Paid", "Advanced", "AI", "Essential", "Interactive", "Backend", "Error", "Fix", "SEO", "Content", "Email", "Social", "Agile", "Scrum", "SaaS", "Startup", "Accounting", "B2B", "Events", "Community", "Virtual"];